{% set name = "msqms" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 35432aa356ed8c34ffec5fb169a82d411e10a49fa69995971c9db0aef0a2060c

build:
  number: 0
  entry_points:
    - print_test = PyDemoTest:test_console_script
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - PyDemoTest
  commands:
    - print_test --help

about:
  home: "https://github.com/liaopan"
  license: MIT-License
  license_family: MIT
  license_file: 
  summary: "TestDemo-Python project for uploading to pypi."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
