# -*- coding: utf-8 -*-
"""Generate MEG Pipeline HTML Report"""
import json
import jinja2

from tqdm.auto import tqdm
from typing import Union
from pathlib import Path
from jinja2 import Environment, PackageLoader

from opmqc.utils.logging import clogger


def gen_quality_report(megfiles: [Union[str, Path]], outdir: Union[str, Path], ftype: str = 'html'):
    """
    Generate HTML/JSON Report for a set of MEG Raw data.
    Parameters
    ----------
    megfiles
    outdir
    ftype:str
        the type of generated report file.
    Returns
    -------
    """
    # validate meg files.

    # validate outdir

    for fmeg in megfiles:
        clogger.info(f"Generating report for {fmeg}")
        qreport = QualityReport(report_data={"Overview": ["Test"]}, minify_html=False)
        if ftype == "json":
            qreport.to_json(outdir)
        else:
            qreport.to_html(outdir)


class QualityReport(object):
    """
    Generate a quality report from MEG raw data.
    """

    def __init__(self,
                 report_data,
                 minify_html,
                 ):
        self.report_data = report_data
        self.minify_html = minify_html

    def to_json(self, out_json_path: Union[str, Path]) -> None:
        """
        write the report to json file
        """
        with tqdm(total=1, desc="Render JSON") as pbar:
            report_data = json.dumps(self.report_data, indent=4)
            pbar.update()
        self._to_file(report_data=report_data, output_file=out_json_path)

    def to_html(self, out_html_path: Union[str, Path]) -> None:
        """
        write the report to html file
        """
        with tqdm(total=1, desc="Render Html") as pbar:
            html = HtmlReport(self.report_data).render_html()

            if self.minify_html:
                import minify_html
                html = minify_html.minify(html,
                                          minify_js=True,
                                          minify_css=True,
                                          )
            pbar.update()

        self._to_file(report_data=html, output_file=out_html_path)

    def _to_file(self, report_data: str, output_file: Union[str, Path]) -> None:
        """
        Write the report to a file.
        """
        if not isinstance(output_file, Path):
            output_file = Path(str(output_file))

        if output_file.suffix not in [".html", ".json"]:
            suffix = output_file.suffix
            output_file = output_file.with_suffix(".html")
            clogger.warning(
                f"Extension {suffix} not supported. We use .html instead."
                f"To remove this warning, please use .html or .json."
            )

        with tqdm(total=1, desc="Export quality report to file") as pbar:
            output_file.write_text(report_data, encoding="utf-8")
            pbar.update()


class HtmlReport(object):
    def __init__(self, report_data):
        # Init Jinja
        package_loader = PackageLoader(package_name="opmqc", package_path="reports/templates")
        self.jinja2_env = Environment(loader=package_loader)

        self.report_data = report_data

        self.nav_title = "<strong>MEG Quality Report</strong>"
        self.info_title_name = "MEG Data Info"
        self.overview_title_name = "MEG Quality Overview"

        # MEG data info
        self.info_tabs = [("Overview", "overview"), ("Subject Info", "subjectinfo"), ("MEG Info", "meginfo")]

        # basic info
        self.info_basic = {
            "Source file": "/Volumes/Touch/Code/osl_practice/MEG2224_EP_4_raw_tsss.fif",
            "Data acquired": "2000-01-01 00:00:00+00:00",
            "Manufacturer": "Elekta",
            "Duration": "480 seconds",
            "Frequency": "1000Hz",
            "Data Size": "600MB",
        }

        # basic subject info
        self.info_subject_dict = {
            "Name": "Demo",
            "Age": "23",
            "Gender": "Male",
        }
        # basic meg info
        self.info_meg_dict = {
            "Channel Type": ["mag", "grad", "stim", "ecg", "eog"],
            "Value": [102, 204, 3, 1, 1]
        }

        self.overview_tabs = ["Overview", "SubjectInfo", "MEGInfo"]
        # self.overview_tabs = ["view", "info", "meg"]

        self.overview_quality_dict = {

        }

        self.footer = 'MEG Quality Report Generated by <a href="https://github.com/liaopan/opmqc">OPMQC</a>.'

    def get_template(self, template_name: str) -> jinja2.Template:
        return self.jinja2_env.get_template(template_name)

    def gen_base_template(self):
        return self.get_template('base.html')

    def gen_html_report(self):
        # navigation settings.
        self.nav_items = [("INFO", "info"),
                          ("Quality Overview", "overview"),
                          ("Artifacts", "artifacts"),
                          ("Visual Inspection", "inspection"),
                          ("ICA", "ica")]

        # get base templates(Main HTML)
        render_params = {
            "title": self.nav_title,
            "nav": True,
            "nav_items": self.nav_items,
            "footer": self.footer,

            "info_title": self.info_title_name,
            "info_tabs": self.info_tabs,

            "info_basic": self.info_basic,
            "info_subject_dict": self.info_subject_dict,
            "info_meg_dict": self.info_meg_dict,

            "overview_title": self.overview_title_name,
            "overview_tabs": self.overview_tabs
            # "overview_dict": self.overview_dict,
        }

        html = self.gen_base_template().render(**render_params)
        return html

    def gen_nav_html(self):
        html = self.get_template("navigation.html")
        # multi panels
        self.nav_items = [("Quality Overview", "overview"),
                          ("Artifacts", "artifacts"),
                          ("Visual Inspection", "inspection"),
                          ("ICA", "ica")]

        html.render(self.nav_items)
        return html

    def gen_body_html(self):
        html = self.get_template("navigation.html")
        # multi panels
        self.nav_items = [("Quality Overview", "overview"),
                          ("Artifacts", "artifacts"),
                          ("Visual Inspection", "inspection"),
                          ("ICA", "ica")]

        html.render(self.nav_items)
        # panel: Quality Overview

        # panel: Artifacts

        # panel: Visual Inpsection

        # panel: ICA(optional)

        return html

    def render_html(self):
        html_page = self.gen_html_report()
        print(html_page)
        return html_page


if __name__ == "__main__":
    navigation_title = "MEG Quality Report"
    navigation_links = ["Quality Overview", "Artifacts", "Quality Visual Inspection", "ICA"]
    gen_quality_report(["/Volumes/Touch/Code/osl_practice/anonymize_raw_tsss.fif"], outdir="./demo_report.html")
